Feature/weekly goals
MTVS-3rd-TODORIAN/TODORIAN_BE pull request #55
Opened 2024-09-12 07:33 UTC by seoweed

## ⭐Key Changes
> 핵심 변경 사항에 대해서 적어주세요.
1. todo entity refactor
2. weekly logic 구현
3. todo, weekly api 구현

<br>

## 📌Issue
> "close #이슈번호"로 해당 이슈 완료해주세요.
close #36 
close #37 

<br>

## 👪To Reviewers
> reviewer에게 하고 싶은 말을 적어주세요.
None
<br>

## 🐾Next Move
> 다음 개발 목표를 적어주세요
point entity 정의 및 서비스 로직 개발

2024-09-13 05:59 UTC, INUK-ai requested changes

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/todo/application/controller/TodoController.java
/todo-day 가 아니라 /todo/{date} 로 하는게 낫지 않나?
당일 확인용으로만 쓸건 아니지 않나?

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/todo/application/service/TodoService.java
같은 맥락

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/todo/domain/model/Todo.java
이거 memberId 는 어디서 저장하냐

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/weeklygoals/command/application/controller/WeeklyGoalsController.java
이것도 dto로 처리해서 return 하셈

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/weeklygoals/command/domain/model/WeeklyGoals.java
djckvl successYN이 N으로 고정이니까 
builder 에서 값을 받아올 필요 없이 그냥 this.successYN = "N" 이라고 해도 되지 않나

2024-09-13 05:59 UTC, INUK-ai commented on src/main/java/com/todorian/weeklygoals/command/domain/model/WeeklyGoals.java
그리고 몇월 몇주차인지는 어떻게 알아?

2024-09-23 14:51 UTC, seoweed commented on src/main/java/com/todorian/weeklygoals/command/domain/model/WeeklyGoals.java
YN값 변경이 일어났을 때 빌더로 만들 수도 있어서 이렇게 해놨습니다. 
몇월 몇주차인지는 1년 주차가 52주라서 일반적인 정수값으로 확인하려고 합니다.

2024-09-23 14:51 UTC, seoweed commented on src/main/java/com/todorian/weeklygoals/command/application/controller/WeeklyGoalsController.java
dto 생성해서 return 하도록 변경했습니다.

2024-09-23 14:51 UTC, seoweed commented on src/main/java/com/todorian/todo/domain/model/Todo.java
todo 생성을 어떻게 할 지 고민해보고 만들겠습니다

2024-09-23 14:51 UTC, seoweed commented on src/main/java/com/todorian/todo/application/service/TodoService.java
넵

2024-09-23 14:51 UTC, seoweed commented on src/main/java/com/todorian/todo/application/controller/TodoController.java
넵 추가하겠습니다.

2024-09-23 14:54 UTC, closed without merging